# -*- coding: utf-8 -*-
{
    "name": "Roles y Permisos para Finanzas",
    "summary": "Control de acceso a funcionalidades de contabilidad según roles",
    "description": "Este módulo implementa restricciones para los grupos basico_finanzas, medio_finanzas, alto_finanzas, y gerencia_finanzas en el módulo de contabilidad.",
    "author": "Tu Nombre",
    "website": "https://www.tuweb.com",
    "category": "Accounting",
    "version": "18.0.1.0.0",
    "depends": ["account"],
    "data": [
        "security/roles_permisos_groups.xml",
        "views/account_menu_inherit.xml",
        "views/account_move_inherit.xml",
        "views/contacts_menu_inherit.xml",
        "views/ent_menu_inherit.xml",
        "views/hr_menu_inherit.xml",
        "views/mail_menu_inherit.xml",
        "views/menu_menu_inherit.xml",
        "views/payment_move_inherit.xml",
        "views/payrol_menu_inherit.xml",
        "views/point_of_sale_menu_inherit.xml",
        "views/purchase_menu_inherit.xml",
        "views/purchase_move_inherit.xml",
        "views/sale_menu_inherit.xml",
        "views/stock_menu_inherit.xml",
        "views/stock_move_inherit.xml",
        "views/mrp_menu_inherit.xml",
        "views/mrp_move_inherit.xml",
        "views/helpdesk_menu_inherit.xml",
        "views/product_move_inherit.xml",
    ],
    "installable": True,
    "application": False,
}
